# Generated by Django 6.0.3 on 2026-04-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("endereco", models.TextField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="usuarios/"),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("cachorro", "Cachorro"),
                            ("gato", "Gato"),
                            ("outro", "Outro"),
                        ],
                        default="cachorro",
                        max_length=20,
                    ),
                ),
                ("raca", models.CharField(blank=True, max_length=100)),
                (
                    "idade",
                    models.PositiveIntegerField(
                        blank=True, help_text="Idade em anos", null=True
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "adotado",
                    models.BooleanField(
                        default=False,
                        help_text="Quando verdadeiro, o pet já foi adotado e não está mais disponível para adoção.",
                    ),
                ),
                ("data_chegada", models.DateTimeField(auto_now_add=True)),
                ("data_adocao", models.DateTimeField(blank=True, null=True)),
                ("foto_url", models.URLField(blank=True)),
                (
                    "adotante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pets_adotados",
                        to="PatinhadoWeb.usuario",
                    ),
                ),
                (
                    "doador",
                    models.ForeignKey(
                        help_text="Usuário que doou o animal.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animais_doacao",
                        to="PatinhadoWeb.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PedidoAdocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("data_pedido", models.DateTimeField(auto_now_add=True)),
                ("data_resposta", models.DateTimeField(blank=True, null=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_adocao",
                        to="PatinhadoWeb.pet",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_adocao",
                        to="PatinhadoWeb.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de adoção",
                "verbose_name_plural": "Pedidos de adoção",
                "ordering": ["-data_pedido"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("solicitante", "animal"), name="unique_pedido_adocao"
                    )
                ],
            },
        ),
    ]
