# Generated by Django 6.0.3 on 2026-04-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatinhadoWeb', '0002_alter_pedidoadocao_id_alter_pet_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pets/%Y/%m/%d/'),
        ),
    ]
